// Code generated by MockGen. DO NOT EDIT.
// Source: nlp.go
//
// Generated by this command:
//
//	mockgen -source=nlp.go -destination=../../mock/nlp.go
//
// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	"github.com/golang/mock/gomock"
)

// MockNLPService is a mock of NLPService interface.
type MockNLPService struct {
	ctrl     *gomock.Controller
	recorder *MockNLPServiceMockRecorder
}

// MockNLPServiceMockRecorder is the mock recorder for MockNLPService.
type MockNLPServiceMockRecorder struct {
	mock *MockNLPService
}

// NewMockNLPService creates a new mock instance.
func NewMockNLPService(ctrl *gomock.Controller) *MockNLPService {
	mock := &MockNLPService{ctrl: ctrl}
	mock.recorder = &MockNLPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNLPService) EXPECT() *MockNLPServiceMockRecorder {
	return m.recorder
}

// GetAnswerFromPrompt mocks base method.
func (m *MockNLPService) GetAnswerFromPrompt(prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswerFromPrompt", prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswerFromPrompt indicates an expected call of GetAnswerFromPrompt.
func (mr *MockNLPServiceMockRecorder) GetAnswerFromPrompt(prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswerFromPrompt", reflect.TypeOf((*MockNLPService)(nil).GetAnswerFromPrompt), prompt)
}
